name = "GGplot"
uuid = "1e05a8e1-7dec-4f9e-9d3d-7df52321841b"
authors = ["G Jake Gebbie <ggebbie@whoi.edu>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
TMI = "582500f6-28c8-4d8f-aabe-b197735ec1d4"

[compat]
PyPlot = "2"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
